### ISSUE TITLE
How to pull in all USWDS components under the Uswds menu of PatternLab?

### ISSUE THREAD

**Issue by alex-hsa** [forumone/gesso-uswds#112]
Hi Dan:

Just installed GUS into a D9 site and got it working fine. Thank you so much for sharing it.

The 'package.json' specified the version 2.12.0 of the USWDS, however it seems PatternLab has pulled in only a subset of the available components.
How do I get the missing USWDS components pulled into PatternLab such as 'Icon list' or 'Step indicator?'

Thank you very much,
Alex

**Comment by coreylafferty** [comment]
@alex-hsa We do not pull in the CSS for every USWDS component out of the box.  If you wanted to add additional ones, you'd create a new subfolder under the USWDS category in the Pattern Lab/theme files and add a new Sass partial in there that pulls in the CSS.

For example,  create a file named `source/_patterns/03-uswds/step-indicator/_step-indicator.scss` and put this line in it:

```
@import 'components/step-indicator';
```

Once you've recompiled the CSS, the step-indicator styles from the USWDS should be available to use.

If you wanted an example of this component to appear in Pattern Lab or wanted to a Twig file that you could include, you'd also need to add a Twig file with markup in it using the step-indicator classes (e.g., `source/_patterns/03-uswds/step-indicator/step-indicator.twig`) and a markdown file with metadata about this component (e.g., `source/_patterns/03-uswds/step-indicator/step-indicator.md`).  

You can look at other components to see similar examples.  Summary-box or tag are fairly simple ones.

**Comment by alex-hsa** [comment]
Hi Corey:

Thank you so much for the detailed response, which was spot on and I had no difficulties importing the USWDS components I am interested in.

You guys did an awesome job with the GUS theme. For me, it was the fastest way getting to use the USWDS within the Drupal.  Really appreciate your effort in sharing the GUS theme.
