### ISSUE TITLE
npm install have lots of issues with npm modules

### ISSUE THREAD

**Issue by mpentela-reisys** [forumone/gesso-uswds#136]
Hi!
I have installed this theme with the given npm and node versions.
When I run npm install I am seeing this message
found 134 vulnerabilities (1 low, 89 moderate, 44 high)
And couldn't run gulp command? Any suggestions please

**Comment by coreylafferty** [comment]
@mpentela-reisys I just did a fresh install and what I saw after `npm install` was `42 vulnerabilities (24 moderate, 18 high)` and running `gulp` or `gulp build` completed.  

What branch or release are you running?  The latest release is 4.7.0, or you can just use download from the 4.x branch.  

On a semi-related note, we will soon be putting out a 5.0 version that no longer uses Gulp or Pattern Lab (replacing the latter with StoryBook).  I expect that to be released sometime this month.

**Comment by coreylafferty** [comment]
@mpentela-reisys Also, if you're seeing gulp is an unknown command, make sure gulp is installed globally. 

`npm install --global gulp-cli`

See the links in our README for more details.
