### ISSUE TITLE
pattern lab instance not found

### ISSUE THREAD

**Issue by mpentela-reisys** [forumone/gesso-uswds#137]
Hi!
I have installed the theme and am able to run the gulp command.
I am seeing page not found when I tried to access the following URL (similar in my local)
http://localhost:8080/themes/gesso/pattern-lab/index.html

appreciate your help
Thank you

**Comment by coreylafferty** [comment]
@mpentela-reisys That's odd.  A couple of questions then...

Does the gulp command complete without any errors?  If not, what errors does it show?

On your local setup, does localhost:8080 take you to your Drupal site? If not, what URL do you use to get to the site?

Is the theme in the directory /themes/gesso?

**Comment by mpentela-reisys** [comment]
Please ignore the previous issue.
The gulp run gave some issues. I have to reinstall sass gulp-sass, fibers, and core-js modules. And rebuild the node-sass module. After updates I see no errors after gulp command. it generated pattern-lab folder inside the theme.

Thank you
