### ISSUE TITLE
Design Tokens compiler adding single quotes, breaking USWDS tokens

### ISSUE THREAD

**Issue by aCyborg** [forumone/gesso-uswds#178]
Hey all,

I've been working on including some of the USWDS theme settings in the `config.design-tokens.yml` file. It looks like the compiler is automatically adding single quotes `'` around any non-integer items. 

This becomes an issue when you attempt to use some of the [USWDS spacing tokens](https://designsystem.digital.gov/design-tokens/spacing-units/#using-spacing-unit-tokens) that have letters such as `1px` or `neg-1px`.

I've included this in my yml:
```
card-border-width: 1px
```
which compiles to
```
$theme-card-border-width: '1px';
```
which throws an error
```
SassError: "'-\"1px\"' is not a valid USWDS margin-horizontal token. Valid tokens: 1px, 2px, 05, 1, 105, 2, 205, 3, neg-1px, neg-2px, neg-05, neg-1, neg-105, neg-2, neg-205, neg-3, neg-4, neg-5, neg-6, neg-7, neg-8, neg-9, neg-10, neg-15, 4, 5, 6, 7, 8, 9, 10, 15, card, card-lg, mobile, 05em, 1em, 105em, 2em, 0, auto"
```

I have a workaround for this, which is to just manually add in my custom theme variables to relevant `.scss` files, but thought I'd flag it in case anyone else runs into this issue!

**Comment by kmonahan** [comment]
Think this one was fixed somewhere along the way. Tested and I see `$theme-card-border-width: 1px` in my compiled `_uswds-theme-settings.artifact.scss` file (without quotes) and using `units($theme-card-border-width)` in `card.scss` compiles to 1px without error.
