### ISSUE TITLE
[blocked] Drush gesso function

### ISSUE THREAD

**Issue by dcmouyard** [forumone/gesso-uswds#41]
The Drush `gesso` function should be renamed to `guswds` and updated to copy from the guswds theme rather than the gesso theme.

**Comment by dcmouyard** [comment]
Currently blocked by forumone/gesso#425

**Comment by mhoffmanWF** [comment]
@dcmouyard the command works by changing lines 90 & 106 in GessoHelperCommands.php to 'guswds'. No change to the function name required.

**Comment by alex-hsa** [comment]
@dcmouyard, confirming that the command 'drush gesso "My Theme"' works after making the changes on lines 90 & 106 as suggested by @mhoffmanWF.
